apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: deployment
  namespace: namespace-workflow-1702401939771
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
        - name: deployment
          image: acrworkflow1702401939771.azurecr.io/image-workflow-1702401939771:latest
          ports:
            - containerPort: 3000