apiVersion: v1
kind: Service
metadata:
  name: deployment
  namespace: namespace-workflow-1702401939771
spec:
  type: LoadBalancer
  selector:
    app: deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000